/**
 * 1. create a project in firebase console
 * 2.in the project install firebase:npm i firebase
 * 3.bring firebase config into your project (from firebase website)
 * 4.by using useAuth create the auth and export it
 * 5.in the login page:create a provider new GoogleAuthProvider()
 * 6.use signInWithPopup and pass auth and provider
 */

/**
 * //SOCIAL LOGIN
 * 1.Firebase project create
 * 2.authintication > config >
 */